# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='content',
        ),
        migrations.AddField(
            model_name='item',
            name='contents',
            field=models.TextField(default=''),
        ),
    ]
