# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-13 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='website',
            new_name='review',
        ),
    ]
