# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-03 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0007_auto_20190103_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
