# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-04 06:35
from __future__ import unicode_literals

import animes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0010_anime_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[animes.validators.validate_genres]),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=120, validators=[animes.validators.validate_name]),
        ),
    ]
